### ISSUE TITLE
Add better blazor samples

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI.Samples#108]
Having both server side/client side samples is a must for us in the future. If we can add some samples about basic Blazor interactions that would be great.

**Comment by richbryant** [comment]
do you want me to throw something together?  

The default Blazor template done in ReactiveUI for each platform, maybe?  Unless you have something better in mind?

**Comment by glennawatson** [comment]
Yeah same example for wasm/server is fine. Any sample is appreciated I'm sure.

**Comment by richbryant** [comment]
PR is open.
