### ISSUE TITLE
[BUG] Razor Component State

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI.Samples#30]
In the Razor example at the moment there is a state bug.

the sources of this library could help:
https://github.com/kekekeks/NObservable
contains sources for fixing those state management issues

the magic happens here mostly https://github.com/kekekeks/NObservable/blob/master/src/NObservable.Blazor/Internals/NObservableBlazorComponentHelper.cs

**Comment by richbryant** [comment]
Suggest we close this one now.  The bug is obsolete.
