### ISSUE TITLE
Request for Xamarin.Mac sample

### ISSUE THREAD

**Issue by ye4241** [reactiveui/ReactiveUI.Samples#49]
**Is your feature request related to a problem? Please describe.**

Need some samples/instructions for Xamarin.Mac.

**Describe the solution you'd like**

Clear steps for create a Xamarin.Mac project and view/viewmodel binding logics.

**Describe alternatives you've considered**

Umm, may be like Xamarin.Forms for Mac?

**Describe suggestions on how to achieve the feature**

Just supply the sample code and instructions.

**Additional context**

I found a wired project for this request, https://developer.xamarin.com/samples/mac/ReactiveUIExample/ , however, I thought it's wrong way to use ReactiveUI in Xamarin.Mac.

**Comment by RLittlesII** [comment]
@ye4241 I am working (slowly unfortunately) on a Xamarin.Mac app sample using ReactiveUI.  May be worth bringing that sample up to date as well.  Out of curiosity, why do you think it's the wrong way to use ReactiveUI with Xamarin.Mac?

**Comment by ye4241** [comment]
@RLittlesII In WPF, it use more elegant way to bind properties between view and viewmodel, such as this.WhenActivated and this.OneWayBind.
However, in this Xamarin.Mac sample. It use some events to bind to source view model.
```csharp
textField.Changed += (o, e) => viewModel.Text = textField.StringValue;
```

**Comment by glennawatson** [comment]
Yeah. That should probably be changed if we bring the sample to the samples repo.

**Comment by RLittlesII** [comment]
Agreed.  Was just making sure you meant using the platform bindings, and not referring to xib and the IB approach.  😁

I use the platform bindings for Xamarin.Mac and Xamarin.iOS.

Good feedback.

**Comment by RLittlesII** [comment]
I am closing this issue as we have added a new Xamarin.Mac sample to the repository.

I see the request for Xamarin.Forms for Mac.  I may circle back and add an example, but the bindings would be no different than any other XF app.  The Xamarin.Mac app would just wrap the XF app.

Documentation on how to create a Xamarin Forms Mac app can be found [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac)
