### ISSUE TITLE
[BUG] ReactiveUI.Samples.Routing101 does not compile

### ISSUE THREAD

**Issue by Mrxx99** [reactiveui/ReactiveUI.Samples#50]
**Describe the bug**

The project ReactiveUI.Samples.Routing101 can't be compiled because there is an error:

> CS0200	Property or indexer 'ILogger.Level' cannot be assigned to -- it is read only	ReactiveUI.Samples.Routing101 ..\ReactiveUI.Samples.Routing\ViewModels\AppBootstrapper.cs	Line 44

**Steps To Reproduce**
1. try to build ReactiveUI.Samples.Routing101

**Expected behavior**
The project should be able to be build.

**Environment**

- OS:       Windows
- Version   10

**Additional context**
A easy workaround is to delete the affected line.

**Comment by glennawatson** [comment]
Happy to have a PR on this one. Thanks for reporting.
