### ISSUE TITLE
WinForms example update to .net Core 6 and latest C# functionality

### ISSUE THREAD

**Issue by rallets** [reactiveui/ReactiveUI.Samples#515]
Hi, I was wondering if you are intersted in accepting a PR in the WinForms example that:
- updates to the latest .net core 6 and C# functionality
- made the VS Designer available for a generic UserControl, that I think can stop a newbie like me to join RxUi
- made the "Open github repo" button working (or at least it was not working for me in Windows 10)
You can check to changes in my fork:
(https://github.com/rallets/ReactiveUI.Samples/commit/ef74506e0973da0ef02cb561a9a65482f886b1a7)

**Comment by glennawatson** [comment]
All the changes in your commit look good. We would be grateful for the PR.
