### ISSUE TITLE
WinForms - new demo project

### ISSUE THREAD

**Issue by rallets** [reactiveui/ReactiveUI.Samples#522]
I just submitted a PR with the a new WinForms demo project. Let me know if I need to improve something!
[PR #518](https://github.com/reactiveui/ReactiveUI.Samples/pull/518)
Ps. the build failed, but because of the Blazor project, I don't think it's related to my PR.

The demo implements:
- Dependency injection with Splat, views, and services.
- How to use a main entry-point with Routing and UserControls.
- How to open a new Form (outside the main routing).
- Routing between screens/views.
- Binding data and execute commands between View and ViewModel.
- Bind to reactive properties (as calculated fields).
- How to bind data to a ListBox via DataSource.
- How to deal with UI events (via `ReactiveMarbles.ObservableEvents.SourceGenerator`).
- How to use Interactions to show Modal form with or without DialogResult.
- How to subscribe to UI changes like TextBox and ComboBox with sort info, and refresh the data in the UI.
- How to use Dynamic Data and deal with Collections. See the note below.
- Unit testing with custom scheduler and time-based scenarios.
- etc.

**Comment by glennawatson** [comment]
Thanks I'll get around to doing a proper review this weekend and probably fix that blazor stuff first. 

Thanks for helping out

**Comment by rallets** [comment]
I think there is a glitch in the ItemsViewModel ItemsFiltered property using `initialValue`. If I remove `initialValue` everything works as expected, otherwise it doesn't update when a new value is emitted and the list remain empty. I'm wondering if you can give me a feedback about this when you review it.
