### ISSUE TITLE
Does ReactiveUI have any sample documentation for F# projects?

### ISSUE THREAD

**Issue by Kavignon** [reactiveui/ReactiveUI.Samples#68]
**Is your feature request related to a problem? Please describe.**

I was taking a look and maybe I searched too quickly but haven’t found samples with F#. Being an FRP library, I thought F# would go in pair with this, no?

**Describe the solution you'd like**

Maybe have a dedicated folder for F# sample projects in the repo?

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

Let’s create small and medium size projects for both desktop and mobile showcasing ReactiveUI with F#

**Additional context**

**Comment by worldbeater** [comment]
Yeah, adding a few up-to-date F# samples is a great idea. For now, we have only old samples https://github.com/reactiveui/ReactiveUI.Samples/tree/master/OldSamples/ReactiveUI.Samples.Basics.FSharp so probably worth improving them. Planning to update those samples sooner than later, but if you wish we'll be really happy to receive a PR. ✨

**Comment by glennawatson** [comment]
There is a bit of a maintenance burden so ideally if you get the samples up and running you'll have them working in the sln file.

**Comment by glennawatson** [comment]
They replaced the packed.config with PackageReference. 

Just a lot cleaner since it handles dependency packages.
