### ISSUE TITLE
Testing Samples

### ISSUE THREAD

**Issue by gordonwatts** [reactiveui/ReactiveUI.Samples#9]
What would you think about adding two testing samples that demonstrate how to test view models? One that doesn't use time travel and one that does? Or similar. I ask because it took me a few hours of fumbling around to learn it, and having something I could copy would have been helped me out.

If this isn't the right place to ask this sort of question, let me know where.

**Comment by ghuntley** [comment]
@gordonwatts this will be covered in the reactiveui/samples repository. I'm closing out this issue, if you are still using RxUI we would love to see you join us over in Slack - https://github.com/reactiveui/reactiveui#slack
